// <auto-generated />
using System;
using KegTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KegTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504141544_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("KegTracker.API.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ABV")
                        .HasColumnType("REAL");

                    b.Property<string>("Brewer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("KegTracker.API.Models.ConsumptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountPouredLitres")
                        .HasColumnType("REAL");

                    b.Property<int>("KegId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PouredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KegId");

                    b.ToTable("ConsumptionLogs");
                });

            modelBuilder.Entity("KegTracker.API.Models.Keg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacityLitres")
                        .HasColumnType("REAL");

                    b.Property<double>("RemainingLitres")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("Kegs");
                });

            modelBuilder.Entity("KegTracker.API.Models.ConsumptionLog", b =>
                {
                    b.HasOne("KegTracker.API.Models.Keg", "Keg")
                        .WithMany()
                        .HasForeignKey("KegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keg");
                });

            modelBuilder.Entity("KegTracker.API.Models.Keg", b =>
                {
                    b.HasOne("KegTracker.API.Models.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");
                });
#pragma warning restore 612, 618
        }
    }
}
